/* kabi-lookup.cpp - search the graph generated by kabi-parser for symbols
 *                   given by the user
 *
 * Copyright (C) 2015  Red Hat Inc.
 * Tony Camuso <tcamuso@redhat.com>
 *
 ********************************************************************************
 * This is free software. You can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *******************************************************************************
 *
 */

#include <vector>
#include <cstring>
#include <fstream>

#include "kabilookup.h"

//#define NDEBUG
#if !defined(NDEBUG)
#define DBG(x) x
#define RUN(x)
#define prdbg(fmt, ...) \
do { \
       printf(fmt, ##__VA_ARGS__); \
} while (0)
#else
#define DBG(x)
#define RUN(x) x
#define prdbg(fmt, ...)
#endif


using namespace std;
using namespace kabilookup;

string lookup::get_helptext()
{
	return "\
\n\
kabi-lookup -[vw] -c|d|e|s symbol [-b datafile]\n\
    Searches a kabi database for symbols. The results of the search \n\
    are printed to stdout and indented hierarchically.\n\
\n\
    -c symbol   - Counts the instances of the symbol in the kabi tree. \n\
    -s symbol   - Prints to stdout every exported function that is implicitly \n\
                  or explicitly affected by the symbol. In verbose mode, the \n\
                  chain from the exported function to the symbol is printed.\n\
                  It is advisable to use \"-c symbol\" first. \n\
    -e symbol   - Specific to EXPORTED functions. Prints the function, \n\
                  and its argument list. With the -v verbose switch, it \n\
                  will print all the descendants of nonscalar arguments. \n\
    -d symbol   - Seeks a data structure and prints its members to stdout. \n\
                  The -v switch prints descendants of nonscalar members. \n\
    -v          - verbose lists all descendants of a symbol. \n\
    -w          - whole words only, default is \"match any and all\" \n\
    -b datafile - Optional sqlite database file. The default is \n\
                  \"../kabi-data.dat\" relative to top of kernel tree. \n\
    --no-dups   - A structure can appear more than once in the nest of an \n\
                  exported function, for example a pointer back to itself as\n\
                  parent to one of its descendants. This switch limits the \n\
                  appearance of a symbol\'s tree to just once. \n\
    -h  this help message.\n";
}

lookup::lookup(int argc, char **argv)
{
	m_err.init(argc, argv);
	if ((m_errindex = process_args(argc, argv))) {
		m_err.print_cmd_errmsg(m_errindex, m_declstr, m_datafile);
		exit(m_errindex);
	}

	if ((m_errindex = execute())) {
		m_err.print_cmd_errmsg(m_errindex, m_declstr, m_datafile);
		exit(m_errindex);
	}
}

int lookup::count_bits(unsigned mask)
{
	int count = 0;

	do {
		count += mask & 1;
	} while (mask >>= 1);

	return count;
}

// Check for mutually exclusive flags.
bool lookup::check_flags()
{
	if (count_bits(m_flags & m_exemask) > 1)
		return false;

	return true;
}

int lookup::process_args(int argc, char **argv)
{
	int argindex = 0;

	// skip over argv[0], which is the invocation of this app.
	++argv; --argc;

	if(!argc)
		return EXE_ARG2SML;

	m_flags = m_opts.get_options(&argindex, &argv[0], m_declstr, m_datafile);

	if (!check_flags())
		return EXE_BADFORM;

	return EXE_OK;
}

int lookup::execute()
{
	switch (m_flags & m_exemask) {
	case KB_COUNT   : return exe_count(m_declstr, m_datafile);
//	case KB_DECL    : return exe_decl(m_declstr, m_datafile);
//	case KB_EXPORTS : return exe_exports(m_declstr, m_datafile);
//	case KB_STRUCT  : return exe_struct(m_declstr, m_datafile);
	}
	return 0;
}

#include <boost/format.hpp>
using boost::format;

const qnode *lookup::find_decl(const vector<qnode> &qnlist,
			       const string &declstr)
{
	const qnode *qn;
	for (unsigned i = 0; i < qnlist.size(); ++i) {
		DBG(qn = &qnlist[i]; \
		cout << format("%08x %08x \"%s\"\n") \
			% qn->cn->crc % qn->flags % qn->sdecl;)
		if (!(qn = &qnlist[i])->sdecl.compare(declstr))
			return qn;
	}
	return NULL;
}

int lookup::get_decl_list(const std::vector<qnode> &qnlist,
		  const std::string &declstr,
		  std::vector<qnode> &retlist)
{
	const qnode *qn;
	for (unsigned i = 0; i < qnlist.size(); ++i) {
		if (!(qn = &qnlist[i])->sdecl.compare(0, declstr.length(), declstr));
		//if ((qn = &qnlist[i])->sdecl.find(declstr) != string::npos)
			retlist.push_back(*qn);
	}
	DBG(cout << format("\"%s\" size: %d\n") % declstr %  declstr.size();)

	return retlist.size();
}

int lookup::exe_count(string &declstr, string &datafile)
{
	kb_read_qlist(datafile, m_qnlist);

	vector<qnode> declist;
	int dlsize = get_decl_list(m_qnlist.qnodelist, declstr, declist);

	DBG(cout << "declist size: " << dlsize << endl;)
	DBG(cout << "qlist size: " << m_qnlist.qnodelist.size()) << endl;

	return EXE_OK;


	const qnode *qn = find_decl(m_qnlist.qnodelist, declstr);

	if (!qn)
		return EXE_NOTFOUND;

	DBG(cout << format("%08x %08x %s\n") \
	    % qn->cn->crc % qn->flags % qn->sdecl;)
	cout << qn->parents.size() << endl;


	return EXE_OK;
}


/************************************************
** main()
************************************************/
int main(int argc, char *argv[])
{
	lookup lu(argc, argv);
}
